# Generated by Django 3.2 on 2021-04-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='post',
        ),
        migrations.RemoveField(
            model_name='points',
            name='topic',
        ),
    ]
